name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*'  # Trigger on pushes to tags starting with 'v' (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'  # Ajuste para a versão de Go que você usa

      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o go-api-gen-linux-amd64 main.go
          GOOS=linux GOARCH=arm64 go build -o go-api-gen-linux-arm64 main.go
          GOOS=darwin GOARCH=amd64 go build -o go-api-gen-macos-amd64 main.go
          GOOS=darwin GOARCH=arm64 go build -o go-api-gen-macos-arm64 main.go

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Linux AMD64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./go-api-gen-linux-amd64
          asset_name: go-api-gen-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Linux ARM64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./go-api-gen-linux-arm64
          asset_name: go-api-gen-linux-arm64
          asset_content_type: application/octet-stream

      - name: Upload macOS AMD64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./go-api-gen-macos-amd64
          asset_name: go-api-gen-macos-amd64
          asset_content_type: application/octet-stream

      - name: Upload macOS ARM64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./go-api-gen-macos-arm64
          asset_name: go-api-gen-macos-arm64
          asset_content_type: application/octet-stream